In [44]:
# ==========================================
# Import Required Libraries
# ==========================================

import pandas as pd
import numpy as np
import joblib

# Machine Learning
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Models
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

# Evaluation
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

import warnings
warnings.filterwarnings("ignore")

print("Libraries Imported Successfully!")

Libraries Imported Successfully!

In [45]:
# ==========================================
# Load Processed Dataset
# ==========================================

data = pd.read_csv('/content/processed_credit_card_data.csv')

print("Dataset Loaded Successfully!")
print("Dataset Shape:", data.shape)

Dataset Loaded Successfully!
Dataset Shape: (36457, 18)

In [46]:
X = data.drop("TARGET", axis=1)
y = data["TARGET"]

In [47]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [48]:
X = data.drop("TARGET", axis=1)
y = data["TARGET"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [49]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

Logistic Regression

In [50]:
 # ==========================================
# Logistic Regression
# ==========================================

lr_model = LogisticRegression(
    random_state=42,
    max_iter=1000
)

lr_model.fit(X_train_scaled, y_train)

lr_predictions = lr_model.predict(X_test_scaled)

lr_accuracy = accuracy_score(y_test, lr_predictions)
lr_precision = precision_score(y_test, lr_predictions)
lr_recall = recall_score(y_test, lr_predictions)
lr_f1 = f1_score(y_test, lr_predictions)
lr_auc = roc_auc_score(y_test, lr_predictions)

print("Accuracy :", lr_accuracy)
print("Precision:", lr_precision)
print("Recall   :", lr_recall)
print("F1 Score :", lr_f1)
print("ROC-AUC  :", lr_auc)

Accuracy : 0.9831321996708722
Precision: 0.0
Recall   : 0.0
F1 Score : 0.0
ROC-AUC  : 0.5

Decision Tree

In [51]:
# ==========================================
# Decision Tree
# ==========================================

dt_model = DecisionTreeClassifier(
    random_state=42,
    class_weight="balanced",
    max_depth=8,
    min_samples_leaf=10
)
dt_model.fit(X_train_scaled, y_train)

dt_predictions = dt_model.predict(X_test_scaled)

dt_accuracy = accuracy_score(y_test, dt_predictions)
dt_precision = precision_score(y_test, dt_predictions)
dt_recall = recall_score(y_test, dt_predictions)
dt_f1 = f1_score(y_test, dt_predictions)
dt_auc = roc_auc_score(y_test, dt_predictions)

print("Accuracy :", dt_accuracy)
print("Precision:", dt_precision)
print("Recall   :", dt_recall)
print("F1 Score :", dt_f1)
print("ROC-AUC  :", dt_auc)

Accuracy : 0.4832693362589139
Precision: 0.01874834961711117
Recall   : 0.5772357723577236
F1 Score : 0.03631713554987212
ROC-AUC  : 0.5294464536220198

Random Forest

In [52]:
# ==========================================
# Random Forest
# ==========================================

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf_model.fit(X_train_scaled, y_train)

rf_predictions = rf_model.predict(X_test_scaled)

rf_accuracy = accuracy_score(y_test, rf_predictions)
rf_precision = precision_score(y_test, rf_predictions)
rf_recall = recall_score(y_test, rf_predictions)
rf_f1 = f1_score(y_test, rf_predictions)
rf_auc = roc_auc_score(y_test, rf_predictions)

print("Accuracy :", rf_accuracy)
print("Precision:", rf_precision)
print("Recall   :", rf_recall)
print("F1 Score :", rf_f1)
print("ROC-AUC  :", rf_auc)

Accuracy : 0.9809380142622052
Precision: 0.35185185185185186
Recall   : 0.15447154471544716
F1 Score : 0.21468926553672316
ROC-AUC  : 0.574794706658184

XGBoost

In [53]:
!pip install xgboost -q

In [54]:
from xgboost import XGBClassifier

In [55]:
# ==========================================
# XGBoost
# ==========================================

xgb_model = XGBClassifier(
    random_state=42,
    eval_metric='logloss'
)

xgb_model.fit(X_train_scaled, y_train)

xgb_predictions = xgb_model.predict(X_test_scaled)

xgb_accuracy = accuracy_score(y_test, xgb_predictions)
xgb_precision = precision_score(y_test, xgb_predictions)
xgb_recall = recall_score(y_test, xgb_predictions)
xgb_f1 = f1_score(y_test, xgb_predictions)
xgb_auc = roc_auc_score(y_test, xgb_predictions)

print("Accuracy :", xgb_accuracy)
print("Precision:", xgb_precision)
print("Recall   :", xgb_recall)
print("F1 Score :", xgb_f1)
print("ROC-AUC  :", xgb_auc)

Accuracy : 0.981897970378497
Precision: 0.3548387096774194
Recall   : 0.08943089430894309
F1 Score : 0.14285714285714285
ROC-AUC  : 0.5433205524690203

Model Comparison

In [56]:
comparison = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Decision Tree",
        "Random Forest",
        "XGBoost"
    ],
    "Accuracy": [
        lr_accuracy,
        dt_accuracy,
        rf_accuracy,
        xgb_accuracy
    ],
    "Precision": [
        lr_precision,
        dt_precision,
        rf_precision,
        xgb_precision
    ],
    "Recall": [
        lr_recall,
        dt_recall,
        rf_recall,
        xgb_recall
    ],
    "F1 Score": [
        lr_f1,
        dt_f1,
        rf_f1,
        xgb_f1
    ],
    "ROC-AUC": [
        lr_auc,
        dt_auc,
        rf_auc,
        xgb_auc
    ]
})

comparison = comparison.sort_values(
    by="F1 Score",
    ascending=False
)

comparison

                 Model  Accuracy  Precision    Recall  F1 Score   ROC-AUC
2        Random Forest  0.980938   0.351852  0.154472  0.214689  0.574795
3              XGBoost  0.981898   0.354839  0.089431  0.142857  0.543321
1        Decision Tree  0.483269   0.018748  0.577236  0.036317  0.529446
0  Logistic Regression  0.983132   0.000000  0.000000  0.000000  0.500000

In [57]:
models = {
    "Logistic Regression": lr_model,
    "Decision Tree": dt_model,
    "Random Forest": rf_model,
    "XGBoost": xgb_model
}

best_model_name = comparison.iloc[0]["Model"]

best_model = models[best_model_name]

print("Best Model:", best_model_name)

Best Model: Random Forest

In [58]:
import joblib

joblib.dump(best_model, "model.pkl")
joblib.dump(scaler, "scaler.pkl")

print("Model, scaler, and encoders saved successfully!")

Model, scaler, and encoders saved successfully!

In [59]:
X = data.drop("TARGET", axis=1)
print(X.columns.tolist())

['CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'FLAG_MOBIL', 'FLAG_WORK_PHONE', 'FLAG_PHONE', 'FLAG_EMAIL', 'OCCUPATION_TYPE', 'CNT_FAM_MEMBERS', 'AGE', 'EMPLOYMENT_YEARS']

In [60]:
print(classification_report(y_test, dt_predictions))

              precision    recall  f1-score   support

           0       0.99      0.48      0.65      7169
           1       0.02      0.58      0.04       123

    accuracy                           0.48      7292
   macro avg       0.50      0.53      0.34      7292
weighted avg       0.97      0.48      0.64      7292

In [61]:
# Find some rejected predictions from the test set

pred = best_model.predict(X_test_scaled)

rejected = X_test[pred == 1]

print("Number of rejected predictions:", len(rejected))

rejected.head(10)

Number of rejected predictions: 54

,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,AGE,EMPLOYMENT_YEARS
36150,0,0,1,0,216000.0,1,4,4,1,1,0,0,0,17,1.0,54,5.457534
31723,1,0,1,0,112500.0,0,1,1,1,1,0,0,0,16,2.0,55,1.520548
35174,0,0,1,0,180000.0,4,4,0,1,1,0,0,0,8,2.0,54,9.884932
22581,1,1,1,2,247500.0,4,4,1,1,1,0,0,0,8,4.0,47,1.465753
28513,0,0,1,0,180000.0,1,4,1,1,1,0,0,0,17,2.0,62,5.457534
11062,1,0,1,1,180000.0,4,3,1,1,1,1,0,0,17,3.0,28,4.635616
36388,0,0,0,0,112500.0,1,4,3,2,1,0,0,0,17,2.0,58,5.457534
36239,1,1,1,1,135000.0,4,1,3,1,1,0,0,0,10,3.0,51,17.421918
33572,1,0,0,1,360000.0,4,1,1,1,1,1,1,0,10,3.0,30,1.284932
29582,0,1,0,0,135000.0,4,2,0,1,1,1,0,0,14,2.0,27,0.600000

In [62]:
original_rejected = X_test.loc[rejected.index]

original_rejected.head()

,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,AGE,EMPLOYMENT_YEARS
36150,0,0,1,0,216000.0,1,4,4,1,1,0,0,0,17,1.0,54,5.457534
31723,1,0,1,0,112500.0,0,1,1,1,1,0,0,0,16,2.0,55,1.520548
35174,0,0,1,0,180000.0,4,4,0,1,1,0,0,0,8,2.0,54,9.884932
22581,1,1,1,2,247500.0,4,4,1,1,1,0,0,0,8,4.0,47,1.465753
28513,0,0,1,0,180000.0,1,4,1,1,1,0,0,0,17,2.0,62,5.457534

In [63]:
pd.set_option('display.max_columns', None)

original_rejected.head(1)

,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,AGE,EMPLOYMENT_YEARS
36150,0,0,1,0,216000.0,1,4,4,1,1,0,0,0,17,1.0,54,5.457534

In [64]:
# Reload the processed dataset before train-test split
data = pd.read_csv("/content/processed_credit_card_data.csv")

# Show the original row using its index
print(data.loc[36150])

CODE_GENDER                 0.000000
FLAG_OWN_CAR                0.000000
FLAG_OWN_REALTY             1.000000
CNT_CHILDREN                0.000000
AMT_INCOME_TOTAL       216000.000000
NAME_INCOME_TYPE            1.000000
NAME_EDUCATION_TYPE         4.000000
NAME_FAMILY_STATUS          4.000000
NAME_HOUSING_TYPE           1.000000
FLAG_MOBIL                  1.000000
FLAG_WORK_PHONE             0.000000
FLAG_PHONE                  0.000000
FLAG_EMAIL                  0.000000
OCCUPATION_TYPE            17.000000
CNT_FAM_MEMBERS             1.000000
TARGET                      1.000000
AGE                        54.000000
EMPLOYMENT_YEARS            5.457534
Name: 36150, dtype: float64

In [66]:
import joblib

joblib.dump(best_model, "model.pkl")
joblib.dump(scaler, "scaler.pkl")

print("Files saved successfully!")

Files saved successfully!

In [67]:
print(best_model)

RandomForestClassifier(random_state=42)